### ISSUE TITLE
能对短链接进行优化？

### ISSUE THREAD

**Issue by specked2527** [JoeanAmier/XHS-Downloader#101]
手机app复制链接
会有垃圾口令 每次都要手动删除非常不方便

类似https://github.com/yt-dlp/yt-dlp
对bilibili的短链接口令就可以直接下载 不用删除垃圾

图片 ![img](https://private-user-images.githubusercontent.com/124735279/340597280-c84fc94a-b6db-4c2a-852d-e114a670eed2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzQ3OTQsIm5iZiI6MTcxODczNDQ5NCwicGF0aCI6Ii8xMjQ3MzUyNzkvMzQwNTk3MjgwLWM4NGZjOTRhLWI2ZGItNGMyYS04NTJkLWUxMTRhNjcwZWVkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxODE0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTNhMDAzYWQ0MWU4NmI3NzJkYmExYjM4OTYxNjM4ZTk1N2FmODZkYTUwNmUwNzg4NmIyNmU0YmE2NjNlMzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RDU_YeLU9tnflUmAfBFM0ILw-zEqKzQcRota4Ehpwos)

https://github.com/JoeanAmier/XHS-Downloader/issues/97#issuecomment-2175504363

还有脚本https://raw.githubusercontent.com/JoeanAmier/XHS-Downloader/master/static/XHS-Downloader.js
在手机上开pc模式也不会显示按钮
每次只能用rdp操作

**Comment by JoeanAmier** [comment]
![image](https://github.com/JoeanAmier/XHS-Downloader/assets/49263334/c268bef9-6521-4866-a059-8e6148d9f11c)

项目最初版本就已经有提取链接功能，无需对口令进行任何处理。

**Comment by specked2527** [comment]
> ![image](https://private-user-images.githubusercontent.com/49263334/341049486-c268bef9-6521-4866-a059-8e6148d9f11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTg1MjcsIm5iZiI6MTcxODc5ODIyNywicGF0aCI6Ii80OTI2MzMzNC8zNDEwNDk0ODYtYzI2OGJlZjktNjUyMS00ODY2LWEwNTktOGU2MTQ4ZDlmMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWZkZGNiZjI0OGM3Zjc3MDM1NjRiZWUxZTQ4NTU3OWRlODhlNWY0MTIyYmE3NDNlOTlkODMwNTg2NDM3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCVNdQFeNOJkL2F7CMZiDXTqgXJDbA_x_RJKAdC6NxE)
> 
> 项目最初版本就已经有提取链接功能，无需对口令进行任何处理。


为啥我的短链接 长这样 app v.8.30
不删除前面的垃圾是没法用的
```21 狗叭哩发布了一篇小红书笔记，快来看吧！ 😆 czUmEjBfVlbIRHb 😆 http://xhslink.com/rDIjRM，复制本条信息，打开【小红书】App查看精彩内容！```

```Microsoft Windows [版 本  10.0.19045.4529]
(c) Microsoft Corporation。 保 留 所 有 权 利 。
ioi@DESKTOP-VTVPH50 C:\Users\ioi>x -u 21 狗 叭 哩 发 布 了 一 篇 小 红 书 笔 记 ， 快 来
看 吧 ！  ?? czUmEjBfVlbIRHb ?? http://xhslink.com/rDIjRM， 复 制 本 条 信 息 ， 打
开 【 小 红 书 】 App查 看 精 彩 内 容 ！
Usage: x [OPTIONS]
Try 'x --help' for help.
Error: Got unexpected extra arguments (狗 叭 哩 发 布 了 一 篇 小 红 书 笔 记 ， 快 来 看
吧 ！  ?? czUmEjBfVlbIRHb ?? http://xhslink.com/rDIjRM， 复 制 本 条 信 息 ， 打 开
【 小 红 书 】 App查 看 精 彩 内 容 ！ )
ioi@DESKTOP-VTVPH50 C:\Users\ioi>x -u 狗狗叭叭哩哩发发布布了了一一篇篇小小红红书书笔笔记记，，快快来来看看
吧 ！  ?? czUmEjBfVlbIRHb ?? http://xhslink.com/rDIjRM，M复 制 本 条 信 息 ， 打 开
【 小 红 书 】 App查p看 精 彩 内 容 ！  ！
Usage: x [OPTIONS]
Try 'x --help' for help.
Error: Got unexpected extra arguments (?? czUmEjBfVlbIRHb ?? http://xhslink.com/rDIjRM， 复 制 本 条 信 息 ， 打 开 【 小 红 书 】 App查 看 精 彩 内 容 ！ )
ioi@DESKTOP-VTVPH50 C:\Users\ioi>x -u http://xhslink.com/rDIjRM，M复M制M本M条M信M息M，M打M开M【M小M红M书M】MApp查p看p精p彩p内p容p！p
开！始！处！理！作！品！：！https://www.xiaohongshu.com/discovery/item/6661882e000000000600609d
文 件  2024-06-06_17.58.06_狗 叭 哩 _IF线 长 发 山 田 凉 限 时 登 录 ！ _1 下 载 成 功
文 件  2024-06-06_17.58.06_狗 叭 哩 _IF线 长 发 山 田 凉 限 时 登 录 ！ _2 下 载 成 功
文 件  2024-06-06_17.58.06_狗 叭 哩 _IF线 长 发 山 田 凉 限 时 登 录 ！ _3 下 载 成 功
作 品 处 理 完 成 ： https://www.xiaohongshu.com/discovery/item/6661882e000000000600609d
ioi@DESKTOP-VTVPH50 C:\Users\ioi> ```

**Comment by JoeanAmier** [comment]
![image](https://github.com/JoeanAmier/XHS-Downloader/assets/49263334/898516b3-276d-47c1-b433-10199d3ea287)

测试正常。

**Comment by specked2527** [comment]
> ![image](https://private-user-images.githubusercontent.com/49263334/341080805-898516b3-276d-47c1-b433-10199d3ea287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDE4ODAsIm5iZiI6MTcxODgwMTU4MCwicGF0aCI6Ii80OTI2MzMzNC8zNDEwODA4MDUtODk4NTE2YjMtMjc2ZC00N2MxLWI0MzMtMTAxOTlkM2VhMjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEyNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMzhmMTc1YWM4ZWU5ODg2MjcyY2NjOWVmZmIzMzAwYWQ3ZGM4ZWM1ZjZiODQ5Y2UxMzc1MmNjODA5ZjYxYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LtYvCpa5zpeeYSvuOEMq-8zGzpN1pNukT8zGcnWiAk)
> 
> 测试正常。

在命令行模式不加 "" 是无法下载的
` .\main.exe -u "21 狗叭哩发布了一篇小红书笔记，快来看吧！ 😆 czUmEjBfVlbIRHb 😆 http://xhslink.com/rDIjRM，复制本条信息，打开【小红书】App查看精彩内容" `

**Comment by JoeanAmier** [comment]
命令行需要引号是终端限制，与项目代码无关。

**Comment by specked2527** [comment]
> 命令行需要引号是终端限制，与项目代码无关。

虽然终端是限制的但https://github.com/yt-dlp/yt-dlp 把空格识别分隔符，每个空格后为网址，不能下载就跳过，就实现了下载bilibilib包含空格的短链接和批量下载功能。
`【可能是你听过最对味的《红颜如霜》-哔哩哔哩】 https://b23.tv/ndbH9zh`
所以小红书的短链接，如果程序支持也是可以不加引号的
`21 狗叭哩发布了一篇小红书笔记，快来看吧！ 😆 czUmEjBfVlbIRHb 😆 http://xhslink.com/rDIjRM，复制本条信息，打开【小红书】App查看精彩内容`

**Comment by JoeanAmier** [comment]
以后可能优化。
