### ISSUE TITLE
获取数据失败

### ISSUE THREAD

**Issue by upperblacksmith** [JoeanAmier/XHS-Downloader#105]
大佬，昨天都能正常使用，今天一用就提示数据获取失败，你们可以正常用吗，我是用的源码跑的

**Comment by Opgeek-1** [comment]
一样

**Comment by JoeanAmier** [comment]
疑似校验 cookie 与 ua 是否一致了。

**Comment by kiko923** [comment]
我换了新的已登录cookie也不行了 麻烦作者看看

**Comment by ippleZ** [comment]
> 我换了新的已登录cookie也不行了 麻烦作者看看

source/module/static.py这个文件里面的UA改成自己的

**Comment by kiko923** [comment]
> > 我换了新的已登录cookie也不行了 麻烦作者看看
> 
> source/module/static.py这个文件里面的UA改成自己的

亲测可以 非常感谢！！！

**Comment by JoeanAmier** [comment]
已推送新的代码，可以通过配置文件直接修改 `User-Agent`。

**Comment by kiko923** [comment]
> 已推送新的代码，可以通过配置文件直接修改 `User-Agent`。

服务器模式怎么提示重构中 我需要用到这个咋办

**Comment by lyglj** [comment]
Releases那里啥时候更新啊

**Comment by JoeanAmier** [comment]
> > 已推送新的代码，可以通过配置文件直接修改 `User-Agent`。
> 
> 服务器模式怎么提示重构中 我需要用到这个咋办

可以自行修改 `2.0` 的 `ua` 就能正常使用。

**Comment by Opgeek-1** [comment]
能否提供截图

**Comment by ross-arch** [comment]
程序运行改哪里
