### ISSUE TITLE
XHS V2.0 not working on my computer (fail to retrieved data)

### ISSUE THREAD

**Issue by Superkaizhen07** [JoeanAmier/XHS-Downloader#109]
i am not good at coding or do anything but 1.9 was working pretty find for me. my purpose of using 2.0 is that i want the file to download all my link without exit. pls help

**Comment by mmmmmmmmmn8023** [comment]
+1

**Comment by Superkaizhen07** [comment]
I found temporary solution for this. 
go to C:\XHS-Downloader-2.0\source\module (anywhere you keep the xhs) 
Then open static.py then edit 'sec-ch-ua': '"Google Chrome";v="126" (your chrome version), and also edit on 'user-agent' change to your chrome version.

**Comment by JoeanAmier** [comment]
Indeed, the failure to obtain data was caused by UA, and it is possible that too many people are using the same UA to obtain data.

**Comment by Superkaizhen07** [comment]
pls guide me how to change UA i cannot do it

**Comment by JoeanAmier** [comment]
Pull the latest code, which can be set in the configuration file.

**Comment by Superkaizhen07** [comment]
I fount it already, same path C:\XHS-Downloader-2.0\source\module 
Then setting.py, I copy cookie from web and paste now everything is working fine

**Comment by Opgeek-1** [comment]
请问下一版可以支持苹果点击菜单栏么
