### ISSUE TITLE
v1.6 beta 无法下载

### ISSUE THREAD

**Issue by RoyRao2333** [JoeanAmier/XHS-Downloader#11]
如图，粘贴后无反应 （macOS源码运行，python 3.12.0）

<img width="1016" alt="image" src="https://github.com/JoeanAmier/XHS-Downloader/assets/31413093/25fbd4c0-f884-42aa-8173-d31e8b3b4a7b">

**Comment by JoeanAmier** [comment]
目前只支持作品完整链接，下次更新会支持分享链接。

**Comment by JoeanAmier** [comment]
这种格式的链接是怎么拿到的？

**Comment by RoyRao2333** [comment]
@JoeanAmier 

小红书app点击分享，复制链接，就会自动生成这种短链

**Comment by JoeanAmier** [comment]
已修复问题，并且支持更多作品链接格式。
