### ISSUE TITLE
转链（http://xhslink.com/xGZ7RN）获取数据失败

### ISSUE THREAD

**Issue by Brilo57** [JoeanAmier/XHS-Downloader#110]
使用http://xhslink.com/xGZ7RN获取数据失败。
通过https://www.xiaohongshu.com/discovery/item/667ecec3000000001d019abb能够成功获取。
是否已经不在支持？之前是可以的。

**Comment by Brilo57** [comment]
{'message': '提取小红书作品链接失败', 'url': 'http://xhslink.com/xGZ7RN', 'data': None}

**Comment by JoeanAmier** [comment]
`2.1` 正式发布会支持短链。
