### ISSUE TITLE
explore_data has no column named 动图地址

### ISSUE THREAD

**Issue by jyu041** [JoeanAmier/XHS-Downloader#123]
已经将整个目录删除掉了，除了Downloads文件夹以外，运行最新（2.1）版本的依旧会显示以下错误：

OperationalError: table explore_data has no column named 动图地址

是不是旧的database文件会存在了什么其他的地方？

**Comment by JoeanAmier** [comment]
删掉旧版生成的 `ExploreData.db` 文件。

**Comment by jyu041** [comment]
找到了！谢谢，原来这个文件在Download文件夹里面。
