### ISSUE TITLE
无法下载内容

### ISSUE THREAD

**Issue by YuzeTT** [JoeanAmier/XHS-Downloader#13]
![image](https://github.com/JoeanAmier/XHS-Downloader/assets/61106448/793a8d35-b58c-4eca-8a2a-9583843116eb)

![image](https://github.com/JoeanAmier/XHS-Downloader/assets/61106448/710b164d-eefe-4161-8b94-a59994841f65)

**Comment by YuzeTT** [comment]
尝试设置自定义cookie后依然无法下载

![image](https://github.com/JoeanAmier/XHS-Downloader/assets/61106448/bee58540-f572-4a52-bb73-8af7e4830d02)

**Comment by winterfish0** [comment]
求助，1.5版本无法下载了

**Comment by JoeanAmier** [comment]
本周会发布新版本。

**Comment by duanmuzr** [comment]
可以下载到视频，但无法下载图片

**Comment by JoeanAmier** [comment]
已修复。
