### ISSUE TITLE
2024.8.2无法使用，昨日8.1还可以正常下载正常使用的

### ISSUE THREAD

**Issue by rixxerget** [JoeanAmier/XHS-Downloader#132]
2024.8.2无法使用，昨日8.1还可以正常下载正常使用的，今天打开之后读取链接下载，出了这个框，我的cookie已经填写

![微信截图_20240802085656](https://github.com/user-attachments/assets/844bfe0f-aa3b-42d3-99ae-057930b04db6)
![微信截图_20240802091204](https://github.com/user-attachments/assets/9d00a041-2308-46cc-b9ec-5e2b76efd4f3)

**Comment by JH9601212** [comment]
同问  我用的是打包文件没有截到报错

**Comment by nwcheroes** [comment]
![屏幕截图 2024-08-02 114233](https://github.com/user-attachments/assets/831ecedf-5bdd-4479-8a61-53eb6e7f6fa3)
同样的错误

**Comment by dashu1995** [comment]
我7月30日就用不了了，目前也不知道怎么办？我在想还有什么其他的软件可以暂时替代用的

**Comment by JoeanAmier** [comment]
小红书规则更新了。

**Comment by 1ninty2** [comment]
是要重新下载吗，更新说最新版本了。2.1
