### ISSUE TITLE
作品数据获取失败？

### ISSUE THREAD

**Issue by xlin689** [JoeanAmier/XHS-Downloader#143]
![20240805225502](https://github.com/user-attachments/assets/880c49be-3ac5-45ed-83e5-017e1c82b17e)
逻辑是先check作品id然后下载，只是check成功但是无法下载？这是什么原因

**Comment by JoeanAmier** [comment]
尝试使用最新源码。

**Comment by vicky121345** [comment]
> 尝试使用最新源码。

大佬，可以更新下安装包吗？

**Comment by SameForYou** [comment]
> 尝试使用最新源码。
我试了一个链接也不行
![屏幕截图 2024-08-06 204312](https://github.com/user-attachments/assets/c165e1a4-f206-4d28-b719-2008564bef93)

**Comment by JoeanAmier** [comment]
![image](https://github.com/user-attachments/assets/f60158fa-35c8-4b9a-b9f7-2df0a79334dc)

测试功能正常。

**Comment by SameForYou** [comment]
> ![image](https://private-user-images.githubusercontent.com/49263334/355436365-f60158fa-35c8-4b9a-b9f7-2df0a79334dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDYzMDAsIm5iZiI6MTcyMjk0NjAwMCwicGF0aCI6Ii80OTI2MzMzNC8zNTU0MzYzNjUtZjYwMTU4ZmEtMzVjOC00YjlhLWI5ZjctMmRmMGE3OTMzNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyMDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGU3OTcyMGRiOTYzZGVlOTI3OGVmNzQ2M2ZiOGNhM2NlMmYxNDcxMTFhNTA2MTNiMTZkN2M1ODBiMGNmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BM_qylP8uSQdQ88NGbFpLh9fB-1pTog44ulTW-4bNvs)
> 
> 测试功能正常。

感谢老哥，原来是我下载了release里面的包，要下载master的包就正常工作了

**Comment by xlin689** [comment]
> 尝试使用最新源码。

重新安装了一遍，还是一样的问题，很奇怪。都是2.2beta为什么完全无法下载
