### ISSUE TITLE
带#标签会导致下载保存的文件名异常

### ISSUE THREAD

**Issue by mortgoupil** [JoeanAmier/XHS-Downloader#148]
![QQ20240807-000422](https://github.com/user-attachments/assets/6ffd05e2-615d-4059-8352-2aea110174b4)
![QQ20240807-000443](https://github.com/user-attachments/assets/3d108a07-fd5e-4478-a9a0-bd13967c5965)
使用中发现部分作品在下载后文件名无法正常显示，会变成字符串，怀疑是因为作品带 #标签 导致的，烦请看一下能否修复？谢谢

**Comment by JoeanAmier** [comment]
提供一下作品链接。

**Comment by mortgoupil** [comment]
带#的都会出现此种情况，例如：https://www.xiaohongshu.com/explore/66a83121000000002701c37f
https://www.xiaohongshu.com/explore/66ae5fdc000000000600f8c5
https://www.xiaohongshu.com/explore/667c3b1d000000001c0226d7

**Comment by JoeanAmier** [comment]
测试发现另一个 Bug，没有重现你说的 Bug，提供一下配置文件内容，Cookie 注意脱敏。

**Comment by mortgoupil** [comment]
[settings.json](https://github.com/user-attachments/files/16560033/settings.json)
![a6d525ec-d43f-4b3e-9ab6-e0b5344f497e](https://github.com/user-attachments/assets/6c09ae7a-ef1e-4226-8e35-a6803026f8cc)
不知道为啥我这里标题之后直接带#标签的视频下载完成就是没法正确显示文件名

**Comment by JoeanAmier** [comment]
不属于 Bug，作品标题为空，自动替换为作品 ID。

```json
{
  "作品标题": "",
  "作品描述": "摄影老师准备好了么～\n#木骨[话题]#\\xa0\\xa0#漫展[话题]#\\xa0\\xa0#cos[话题]#"
}
```
