### ISSUE TITLE
有大佬知道iOS 怎么使用 或者  根据这个脚本  改进到iOS吗

### ISSUE THREAD

**Issue by Nododo** [JoeanAmier/XHS-Downloader#151]

**Comment by Nododo** [comment]
> 服务器模式+快捷指令可以实现
你好  服务器接口地址是什么呀？需要自己搭建吗？

**Comment by danielchan-25** [comment]
服务器接口地址要在你的服务器上部署后才有，云服务器或内网穿透等有个公网IP就可以了

**Comment by Nododo** [comment]
> 服务器接口地址要在你的服务器上部署后才有，云服务器或内网穿透等有个公网IP就可以了

好的  感谢哈
