### ISSUE TITLE
这个什么个情况啊，全失败

### ISSUE THREAD

**Issue by ouyanglxy** [JoeanAmier/XHS-Downloader#154]
![image](https://github.com/user-attachments/assets/aa0f65f2-0179-4d83-951f-ed5e220822e3)

**Comment by ouyanglxy** [comment]
https://www.xiaohongshu.com/explore/66a36a94000000000d031ab3
https://www.xiaohongshu.com/explore/66b9d9f2000000000503bd41
https://www.xiaohongshu.com/explore/66b9ca26000000000503a85c
https://www.xiaohongshu.com/explore/66b96739000000000d03068f
https://www.xiaohongshu.com/explore/66b960d100000000050388d4
https://www.xiaohongshu.com/explore/66b4a8430000000005032995
https://www.xiaohongshu.com/explore/66b43be8000000000d0335f4
https://www.xiaohongshu.com/explore/66b1cdb200000000050236b1
https://www.xiaohongshu.com/explore/66b18d520000000009017395
https://www.xiaohongshu.com/explore/66b044b40000000005033f57
https://www.xiaohongshu.com/explore/66af75b30000000005038bf1
https://www.xiaohongshu.com/explore/66ad9410000000000d0313b5
https://www.xiaohongshu.com/explore/66ac9786000000000d0310a4
https://www.xiaohongshu.com/explore/66ac552d0000000009014ab3
https://www.xiaohongshu.com/explore/66ab50d9000000000d031d08
https://www.xiaohongshu.com/explore/66a9b6230000000009017131
https://www.xiaohongshu.com/explore/66a9b74c000000000503877e
https://www.xiaohongshu.com/explore/66a99dd00000000005023b1a
https://www.xiaohongshu.com/explore/66a8a84a000000000503b6a1
https://www.xiaohongshu.com/explore/66a84021000000000901554e
https://www.xiaohongshu.com/explore/66a7164a0000000005032711
https://www.xiaohongshu.com/explore/66a6ec98000000000503aee0
https://www.xiaohongshu.com/explore/66a31c64000000000a007809
https://www.xiaohongshu.com/explore/66a216ad00000000050055fc
https://www.xiaohongshu.com/explore/66a1d5a4000000000a006dc2
https://www.xiaohongshu.com/explore/66a1b5680000000005006e54
https://www.xiaohongshu.com/explore/66a0d25e000000000d00cc68
https://www.xiaohongshu.com/explore/66a082e800000000030275c3
https://www.xiaohongshu.com/explore/669f7ab5000000000d00ecb1
https://www.xiaohongshu.com/explore/669f10aa0000000005004cb6
https://www.xiaohongshu.com/explore/669e4795000000000d00d542
https://www.xiaohongshu.com/explore/669e464d000000000d00c639
https://www.xiaohongshu.com/explore/669e3642000000000a0251ee
https://www.xiaohongshu.com/explore/6694a41200000000030240de
https://www.xiaohongshu.com/explore/6690e8050000000005007d55
https://www.xiaohongshu.com/explore/6690e3330000000003026775
https://www.xiaohongshu.com/explore/6690af030000000003025f1d
https://www.xiaohongshu.com/explore/669086d1000000000a027990
https://www.xiaohongshu.com/explore/668f8c27000000000d00cc08
https://www.xiaohongshu.com/explore/668f399a000000000d00fd36
https://www.xiaohongshu.com/explore/668d287a0000000003026b2f
https://www.xiaohongshu.com/explore/668cae50000000000a026977
https://www.xiaohongshu.com/explore/668b55a5000000000a0240e8
https://www.xiaohongshu.com/explore/6683d2f0000000000a0252a5
https://www.xiaohongshu.com/explore/6684bb07000000000a025da3
https://www.xiaohongshu.com/explore/66821475000000001c028a97
https://www.xiaohongshu.com/explore/667e8fa1000000001c0296a4
https://www.xiaohongshu.com/explore/667e894c000000001c02130e
https://www.xiaohongshu.com/explore/667ccbf4000000001c020675
https://www.xiaohongshu.com/explore/667a328d000000001d01b49d
https://www.xiaohongshu.com/explore/6679388f000000001d018978
https://www.xiaohongshu.com/explore/66791d48000000001c02a3dc
https://www.xiaohongshu.com/explore/66752d79000000001d01b731
https://www.xiaohongshu.com/explore/6673e0ee000000001c03427e
https://www.xiaohongshu.com/explore/66724013000000001c034b28
https://www.xiaohongshu.com/explore/6666bc41000000001501255c
https://www.xiaohongshu.com/explore/666577bb000000000c01a6fa
https://www.xiaohongshu.com/explore/6664f7f1000000000c019bb4
https://www.xiaohongshu.com/explore/665fc8130000000015013a04
https://www.xiaohongshu.com/explore/665dccbf000000000f00f037
https://www.xiaohongshu.com/explore/665bf008000000000c01a3e3
https://www.xiaohongshu.com/explore/6658346400000000150117f0
https://www.xiaohongshu.com/explore/665832c0000000000c01a6e7
https://www.xiaohongshu.com/explore/6656f195000000001303f1b0
https://www.xiaohongshu.com/explore/66559748000000000c019c8e
https://www.xiaohongshu.com/explore/665489b50000000015013bc1

**Comment by ouyanglxy** [comment]
链接在这里，都失败

**Comment by zhangfeifei0907** [comment]
我也是同样的情况

**Comment by zhangfeifei0907** [comment]
检测新版本也失败
![image](https://github.com/user-attachments/assets/5b3d254d-4dab-4cda-b3e9-2557a40e5125)

**Comment by specked2527** [comment]
+1

**Comment by hgjhuang** [comment]
+1

**Comment by U0hZiY** [comment]
停止更新了吗  我也是失败=。=

**Comment by LeonRui** [comment]
我也是一样的情况，MacOS
