### ISSUE TITLE
程序运行  的安装包 运行后一直提示无法下载

### ISSUE THREAD

**Issue by zhengzhiwu-git** [JoeanAmier/XHS-Downloader#157]
程序运行  的安装包 运行后一直提示无法下载，如下截图
![image](https://github.com/user-attachments/assets/6d612d18-8c5b-4173-90ea-ce607239edd1)

**Comment by zhengzhiwu-git** [comment]
使用新版本 2.2版本就可以正常下载了

**Comment by bigdiudiu** [comment]
装了 弄了cookie，也不知道哪里问题  还是获取失败  笨笨的我 默默的等懒人包
