### ISSUE TITLE
部分格式链接无法解析

### ISSUE THREAD

**Issue by kiko923** [JoeanAmier/XHS-Downloader#164]
不可解析的链接如下
`https://www.xiaohongshu.com/explore/66bf0663000000001e019e8c`
不携带xsec_token无法解析
![cc82f9c6bcf1748622636f3a4eadc98.png](https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_5ce8fa6484ccd9e07555b9c743e3f5ea_2579861724630818983.png)

可以解析的链接如下
`https://www.xiaohongshu.com/explore/66bf0663000000001e019e8c?xsec_token=ABzM15091n9KRCCt45q0u13KXhRP3eAQH3Afd263wArTo=`
携带了`xsec_token`参数 可以解析
![d0c3612dba36767c3bd9869a52f4d18.png](https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_88c9536f326824f4ca6466683fb7a44d_2579861724630847896.png)

**Comment by JoeanAmier** [comment]
不带 `xsec_token` 参数需要登录的 `cookie`。

**Comment by kiko923** [comment]
> 不带 `xsec_token` 参数需要登录的 `cookie`。

当前就是带了`cookie`的情况下出现的

**Comment by JoeanAmier** [comment]
![image](https://github.com/user-attachments/assets/cb76fc2a-64ad-44da-808d-935e603f8ac4)

测试正常。
