### ISSUE TITLE
最新2.2正式版 总是ReadError(")

### ISSUE THREAD

**Issue by fuschenkin** [JoeanAmier/XHS-Downloader#170]
下载很缓慢，一个图片出现七八次 readerror  最后才能成功

![微信截图_20240904103917](https://github.com/user-attachments/assets/d91346ea-be28-4529-939b-bee824000d24)

**Comment by fuschenkin** [comment]
保存格式png时候会这样   webp不会   但是我电脑不能看webp格式

**Comment by JoeanAmier** [comment]
更换 UA 或 IP。
