### ISSUE TITLE
每一条下载都会网络异常大家会吗

### ISSUE THREAD

**Issue by 18750911830** [JoeanAmier/XHS-Downloader#182]
![Uploading image.png…]()
有一些文件可以下载成功 有一些就重试五次后失败了

**Comment by 18750911830** [comment]
![Uploading Snipaste_2024-10-08_10-35-46.png…]()

**Comment by peachtower** [comment]
一样的，read error，总要重试很多次，才能成功。

**Comment by JoeanAmier** [comment]
尝试更新 UA 或 IP。

**Comment by peachtower** [comment]
啥是UA？怎么更换UA和IP？你是指用VPN代理吗？

**Comment by mmmmmmmmmn8023** [comment]
> 尝试更新 UA 或 IP。

大佬 更新UA换IP后也是同样的问题

**Comment by zzpop** [comment]
![image](https://github.com/user-attachments/assets/6904ff6a-1d87-4905-ba52-9083125a1830)
一样的呢
