### ISSUE TITLE
作品名称中有"/  _"的时候可能或导致获取数据失败

### ISSUE THREAD

**Issue by aflyingtree** [JoeanAmier/XHS-Downloader#184]
天丝棉的汉服真的不热/六一穿什么 - 羊君的日常 | 小红书 - 你的生活指南】https://www.xiaohongshu.com/discovery/item/6464aea3000000001303f52a
作品链接如上

**Comment by JoeanAmier** [comment]
测试正常，需要使用完整链接，例如：`https://www.xiaohongshu.com/explore/作品ID?xsec_token=密钥&xsec_source=pc_user`

**Comment by aflyingtree** [comment]
https://www.xiaohongshu.com/explore/6464aea3000000001303f52a?xsec_token=ABDtieYLnSHXTzkoYLziWSuDXTLv_uQSd4XidrvrtsU08=&xsec_source=pc_user 
使用了完整地址尝试下载,仍旧报错了
![Snipaste_2024-10-20_14-04-25](https://github.com/user-attachments/assets/bde2d327-7fb4-41d9-bdcf-f0ba5bdac6c4)

**Comment by JoeanAmier** [comment]
![image](https://github.com/user-attachments/assets/5bd41936-5b65-4f06-8211-5837e993672b)

**Comment by aflyingtree** [comment]
ok,非常感谢,我切换网络试试.
