### ISSUE TITLE
PNG图片存在两大问题，可以改成用户上传的默认格式

### ISSUE THREAD

**Issue by najloa** [JoeanAmier/XHS-Downloader#208]
1. 通过比较脚本下载和用户上传的原图，可以看出来PNG比原图更暗。测试步骤：拖放两张图片到浏览器里，来回快速切换两个标签页，比较图片的差别。

2. PNG的占用大小很虚，同分辨率在肉眼不可辨别画质的情况下PNG的占用要比默认格式大十几倍。

**Comment by JoeanAmier** [comment]
数据和文件均从小红书服务器获取。
