### ISSUE TITLE
很好的脚本希望增加其他平台版本

### ISSUE THREAD

**Issue by strikewelkin** [JoeanAmier/XHS-Downloader#56]
很好的脚本，期待长期更新，希望同时希望能在Chrome市场推出扩展插件，以及能开发安卓手机APP适配的外挂模块

**Comment by cser18** [comment]
你自己不能写一个么

**Comment by strikewelkin** [comment]
> 你自己不能写一个么

傻逼

**Comment by cser18** [comment]
> > 你自己不能写一个么
> 
> 傻逼

弱智东西 给你源码 自己写的能力都没有 天天伸手  不会写代码直接撞死得了

**Comment by strikewelkin** [comment]
> > > 你自己不能写一个么
> > 
> > 
> > 傻逼
> 
> 弱智东西 给你源码 自己写的能力都没有 天天伸手 不会写代码直接撞死得了

杂种居然会说人话，不可思议，说这是畜生都是对畜生的侮辱。让各国用户来这世界代码平台看这杂种稀奇生物，有妈生没妈养。好可怜。

**Comment by cser18** [comment]
> > > > 你自己不能写一个么
> > > 
> > > 
> > > 傻逼
> > 
> > 
> > 弱智东西 给你源码 自己写的能力都没有 天天伸手 不会写代码直接撞死得了
> 
> 杂种居然会说人话，不可思议，说这是畜生都是对畜生的侮辱。让各国用户来这世界代码平台看这杂种稀奇生物，有妈生没妈养。好可怜。

一个可怜的伸手党 估计连出生都是伸手来的 让全世界看看伸手党的可怜表情  不知道是不是伸手才生出来你这出生  笑死我了

**Comment by cser18** [comment]
> > > > > 你自己不能写一个么
> > > > 
> > > > 
> > > > 傻逼
> > > 
> > > 
> > > 弱智东西 给你源码 自己写的能力都没有 天天伸手 不会写代码直接撞死得了
> > 
> > 
> > 杂种居然会说人话，不可思议，说这是畜生都是对畜生的侮辱。让各国用户来这世界代码平台看这杂种稀奇生物，有妈生没妈养。好可怜。
> 
> 一个可怜的伸手党 估计连出生都是伸手来的 让全世界看看伸手党的可怜表情 不知道是不是伸手才生出来你这出生 笑死我了

全靠伸手  让你自己写一个 还学狗咬人  出生就应该在家待着  别人还以为国人都是你这种伸手出生呢  别回复了  一辈子靠伸手活着吧

**Comment by strikewelkin** [comment]
> > > > > > 你自己不能写一个么
> > > > > 
> > > > > 
> > > > > 傻逼
> > > > 
> > > > 
> > > > 弱智东西 给你源码 自己写的能力都没有 天天伸手 不会写代码直接撞死得了
> > > 
> > > 
> > > 杂种居然会说人话，不可思议，说这是畜生都是对畜生的侮辱。让各国用户来这世界代码平台看这杂种稀奇生物，有妈生没妈养。好可怜。
> > 
> > 
> > 一个可怜的伸手党 估计连出生都是伸手来的 让全世界看看伸手党的可怜表情 不知道是不是伸手才生出来你这出生 笑死我了
> 
> 全靠伸手 让你自己写一个 还学狗咬人 出生就应该在家待着 别人还以为国人都是你这种伸手出生呢 别回复了 一辈子靠伸手活着吧

不和杂种一般见识，继续叫吧。大伙来看猴戏。

**Comment by SenjuObito** [comment]
> > > > > > > 你自己不能写一个么
> > > > > > 
> > > > > > 
> > > > > > 傻逼
> > > > > 
> > > > > 
> > > > > 弱智东西 给你源码 自己写的能力都没有 天天伸手 不会写代码直接撞死得了
> > > > 
> > > > 
> > > > 杂种居然会说人话，不可思议，说这是畜生都是对畜生的侮辱。让各国用户来这世界代码平台看这杂种稀奇生物，有妈生没妈养。好可怜。
> > > 
> > > 
> > > 一个可怜的伸手党 估计连出生都是伸手来的 让全世界看看伸手党的可怜表情 不知道是不是伸手才生出来你这出生 笑死我了
> > 
> > 
> > 全靠伸手 让你自己写一个 还学狗咬人 出生就应该在家待着 别人还以为国人都是你这种伸手出生呢 别回复了 一辈子靠伸手活着吧
> 
> 不和杂种一般见识，继续叫吧。大伙来看猴戏。

路过，看猴戏，你确实没人脸

**Comment by strikewelkin** [comment]
@chirshk 想不到跟屁虫
