### ISSUE TITLE
小红书笔记正文可以下载吗，txt格式的，放在笔记同一个文件夹里

### ISSUE THREAD

**Issue by PD-1004** [JoeanAmier/XHS-Downloader#77]
大佬，软件很好用，感谢！（已赞赏），另外，想了解下小红书笔记正文可以支持下载吗，试了下目前好像还不行

**Comment by JoeanAmier** [comment]
开启储存作品信息后，作品信息会储存至 `ExploreData.db` 文件，文件类型为 `SQLite`，需要使用支持数据库的程序访问。

旧版本是使用 TXT 保存作品信息的，但是 TXT 不适合储存表格型数据，新版本改成 `SQLite` 了。

**Comment by PD-1004** [comment]
好的谢谢，之前没了解过这个文件，还不知道干嘛的，刚刚试了一下，这里补上导出excel的步骤，方便没接触的小白学习：
--------------------------------------
1. 官网下载并安装sqlite：https://sqlitestudio.pl
2. 找到大佬软件下载目录中的“ExploreData.db”文件，右键选择打开方式，找到并选择”sqlite.exe应用启动程序“
3. 软件打开以后，点上方的【数据】就可以看到整张表格数据了
4. 点击“导出表”蓝色图标（快捷键Ctrl+E），在弹出的窗口点击“next”，在新弹出的【导出格式和选项】窗口，设置【导出格式】为"csv"，自定义设置"输出路径"， 【导出格式选项】勾选“第一行是列名”，点击“finish"按钮即可完成导出。
5. 找到该csv文件，用excel打开就行。
