### ISSUE TITLE
部分笔记内容获取失败，需要更丰富的cookie

### ISSUE THREAD

**Issue by pkilller** [JoeanAmier/XHS-Downloader#86]
下载器非常强，很好用。但是发现偶尔会遇到部分笔记无法下载： 如：https://www.xiaohongshu.com/explore/66343e00000000001e02d744

简单分析了下，这些笔记需要的cookie比普通笔记更多，https://xiaohongshu.com云端直接返回的cookie太少。
而是需要浏览器访问https://xiaohongshu.com/explore得到的cookie才可以正常请求到笔记内容（需要js生成的cookie）。

感谢大佬，工具很好用。

**Comment by JoeanAmier** [comment]
按照 README 说明获取 `Cookie` 即可。
