### ISSUE TITLE
有的笔记下载体积不一样

### ISSUE THREAD

**Issue by xintonglaile** [JoeanAmier/XHS-Downloader#87]
https://www.xiaohongshu.com/explore/6512c9fb000000002101d189
这个笔记用网页解析可以下载3G多的，用软件解析只有200M左右。

**Comment by xintonglaile** [comment]
https://dlpanda.com/zh-CN/xiaohongshu，用这个网页解析是3G的

**Comment by xintonglaile** [comment]
200M左右下的是HVC1格式的

**Comment by JoeanAmier** [comment]
使用的接口不一样，下版本可能会更新接口。
