### ISSUE TITLE
程序运行已配置cookie仍无法下载笔记文字内容

### ISSUE THREAD

**Issue by simonwang8916** [JoeanAmier/XHS-Downloader#88]
程序运行已配置cookie仍无法下载笔记文字内容

**Comment by JoeanAmier** [comment]
测试无异常。

**Comment by JoeanAmier** [comment]
![image](https://github.com/JoeanAmier/XHS-Downloader/assets/49263334/c9f6e36f-c3b3-43b8-bb7a-f2e262065453)

**Comment by simonwang8916** [comment]
昨天试可以了，谢谢博主！
