### ISSUE TITLE
【疑问】使用这个程序会有封IP,封设备的风险吗

### ISSUE THREAD

**Issue by Alwayswei680** [JoeanAmier/XHS-Downloader#89]
非常感谢大佬的程序，免费且开源，作为小白很想咨询一下，会因为高频访问主网站而被封IP和封设备吗？（应该不会封号，因为都没有登录），如何避免被这种情况呢？

**Comment by Alwayswei680** [comment]
以及如果想使用代理，对应的setting.JSON文件中proxy这里应该输入什么内容呢！求解答！

**Comment by JoeanAmier** [comment]
可能封 IP，不太可能封设备，怕封号可以使用未登录的 Cookie。

配置文件有代理参数。

**Comment by Zzzzz188** [comment]
感谢您解答，proxy后面本来是null，此处需要什么代理参数呢？我尝试写过127.0.0.1，似乎无效，辛苦大佬解答~

**Comment by Alwayswei680** [comment]
感谢您解答，proxy后面本来是null，此处需要什么代理参数呢？我尝试写过127.0.0.1，似乎无效，辛苦大佬解答~

**Comment by Alwayswei680** [comment]
感谢，细致有逻辑！
