### ISSUE TITLE
【请问】未来脚本会支持修改我的喜欢/收藏/发布的自动滚动次数？

### ISSUE THREAD

**Issue by simonwang8916** [JoeanAmier/XHS-Downloader#92]
或者能自定义采集一个时间段内的全部链接呢？

**Comment by JoeanAmier** [comment]
脚本已支持自动滚动功能；下版本会优化跳过逻辑，效率更高。

**Comment by simonwang8916** [comment]
修改自动滚动屏幕次数不支持我的点赞/收藏/发布作品，这个能加入吗？

**Comment by simonwang8916** [comment]
明白作者大大意思了，可以手动滚动到所需的作品处停止。

**Comment by JoeanAmier** [comment]
> 修改自动滚动屏幕次数不支持我的点赞/收藏/发布作品，这个能加入吗？

已经支持了，有异常可以反馈。
