### ISSUE TITLE
请教自定义文件名

### ISSUE THREAD

**Issue by zhouuuuuuj** [JoeanAmier/XHS-Downloader#98]
大大，目前自定义文件名默认到分秒，连接符是下划线，我想用2024XXXX【作者昵称】的格式来自定义文件名，时间格式我修改成功了，但是这个连接字符我不知道咋弄，我改了几处地方，但是下载后连接符还是下划线，由于我只是一个半吊子，只好又来请教大大了，还望大佬指点应该修改哪里的代码，非常感谢~~
另外作者ID实在太长了，请问下能获取到作者的小红书号吗，就是一串数字的那个

**Comment by zhouuuuuuj** [comment]
研究了两天居然给我研究成功了，哈哈哈

**Comment by XINGYUOU** [comment]
> 研究了两天居然给我研究成功了，哈哈哈

请问如何获取作者的小红书号

**Comment by zhouuuuuuj** [comment]
> > 研究了两天居然给我研究成功了，哈哈哈
> 
> 请问如何获取作者的小红书号

我只是研究成功了按我自己的习惯命名，小红书号还是不会的，不好意思
